// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isfdoislunocckpnaclw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZmRvaXNsdW5vY2NrcG5hY2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODIxNzIsImV4cCI6MjA2NzQ1ODE3Mn0.q1C5ysOmDluHRe3CZauZEzDftqb9R8d3pYHiH79wm8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});